### ISSUE TITLE
No Update for content.file ?

### ISSUE THREAD

**Issue by bogacg** [cydneymikel/node-box-sdk#2]
I've been trying to update a file entity but it seems **update** function is not implemented for file object under **content**. Is that correct?
![box_api_file_udate_q](https://cloud.githubusercontent.com/assets/5073927/13898518/985488ec-eddc-11e5-8a82-a5f9e6b14217.jpg)

**Comment by cydneymikel** [comment]
@Correct.  Currently update is not implemented - I believe this is noted in the READ.me.  I am happy to take pull requests or attempt to work on getting this implemented soon.

**Comment by cydneymikel** [comment]
Added support for box.content.file.update in version 0.1.7 on npm.
